# Generated by Django 5.2.4 on 2026-08-13 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting upload'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('tiles_version', models.CharField(blank=True, max_length=32)),
                ('tms_scheme', models.BooleanField(default=False, help_text='Enable if the uploaded tiles use TMS (y-flipped) ordering instead of XYZ.')),
                ('center_lat', models.FloatField(blank=True, null=True)),
                ('center_lng', models.FloatField(blank=True, null=True)),
                ('min_zoom', models.PositiveSmallIntegerField(default=0)),
                ('max_zoom', models.PositiveSmallIntegerField(default=22)),
                ('ingest_error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
