# Generated by Django 5.2.4 on 2026-08-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='kind',
            field=models.CharField(choices=[('point', 'Point'), ('line', 'Line')], default='point', max_length=10),
        ),
        migrations.AddField(
            model_name='annotation',
            name='path',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
