# Generated by Django 5.2.4 on 2026-08-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_annotation_kind_annotation_path_alter_annotation_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='kind',
            field=models.CharField(choices=[('point', 'Point'), ('line', 'Line'), ('polygon', 'Polygon')], default='point', max_length=10),
        ),
    ]
